-- ==============================================================================
-- MEMBER 4: ESMA ARICI - ORDER ENGINE & TRANSACTION SCRIPT
-- ==============================================================================

-- 1. SİPARİŞ TABLOLARINI OLUŞTURMA (DDL)
create table orders (
   order_id    number generated by default as identity primary key,
   customer_id number not null,
   shop_id     number not null,
   courier_id  number,
   coupon_id   number,
   total_price number(10,2) default 0,
   status      varchar2(20) default 'PENDING',
   order_date  timestamp default current_timestamp,
   constraint fk_ord_cust foreign key ( customer_id )
      references users ( user_id ),
   constraint fk_ord_shop foreign key ( shop_id )
      references shop ( shop_id ),
   constraint fk_ord_cour foreign key ( courier_id )
      references users ( user_id ),
   constraint fk_ord_coup foreign key ( coupon_id )
      references coupons ( id )
);

create table orderdetails (
   detail_id  number generated by default as identity primary key,
   order_id   number not null,
   product_id number not null,
   quantity   number not null,
   unit_price number(10,2) not null,
   constraint fk_det_order foreign key ( order_id )
      references orders ( order_id )
         on delete cascade,
   constraint fk_det_prod foreign key ( product_id )
      references products ( product_id )
);

-- 2. ORDERS TABLOSU İÇİN 25 ÖRNEK VERİ
insert into orders (
   customer_id,
   shop_id,
   courier_id,
   coupon_id,
   total_price,
   status
) values ( 101,
           1,
           51,
           1,
           500.00,
           'DELIVERED' );
insert into orders (
   customer_id,
   shop_id,
   courier_id,
   coupon_id,
   total_price,
   status
) values ( 102,
           2,
           52,
           2,
           320.00,
           'DELIVERED' );
insert into orders (
   customer_id,
   shop_id,
   courier_id,
   coupon_id,
   total_price,
   status
) values ( 103,
           3,
           53,
           null,
           180.00,
           'SHIPPED' );
insert into orders (
   customer_id,
   shop_id,
   courier_id,
   coupon_id,
   total_price,
   status
) values ( 104,
           4,
           54,
           null,
           150.00,
           'PENDING' );
insert into orders (
   customer_id,
   shop_id,
   courier_id,
   coupon_id,
   total_price,
   status
) values ( 105,
           5,
           55,
           3,
           240.00,
           'DELIVERED' );
insert into orders (
   customer_id,
   shop_id,
   courier_id,
   coupon_id,
   total_price,
   status
) values ( 106,
           6,
           56,
           null,
           290.00,
           'SHIPPED' );
insert into orders (
   customer_id,
   shop_id,
   courier_id,
   coupon_id,
   total_price,
   status
) values ( 107,
           7,
           57,
           4,
           840.00,
           'DELIVERED' );
insert into orders (
   customer_id,
   shop_id,
   courier_id,
   coupon_id,
   total_price,
   status
) values ( 108,
           8,
           58,
           null,
           350.00,
           'PENDING' );
insert into orders (
   customer_id,
   shop_id,
   courier_id,
   coupon_id,
   total_price,
   status
) values ( 109,
           9,
           59,
           null,
           475.00,
           'DELIVERED' );
insert into orders (
   customer_id,
   shop_id,
   courier_id,
   coupon_id,
   total_price,
   status
) values ( 110,
           10,
           60,
           5,
           450.00,
           'SHIPPED' );
insert into orders (
   customer_id,
   shop_id,
   courier_id,
   coupon_id,
   total_price,
   status
) values ( 111,
           11,
           61,
           null,
           330.00,
           'DELIVERED' );
insert into orders (
   customer_id,
   shop_id,
   courier_id,
   coupon_id,
   total_price,
   status
) values ( 112,
           12,
           62,
           null,
           420.00,
           'PENDING' );
insert into orders (
   customer_id,
   shop_id,
   courier_id,
   coupon_id,
   total_price,
   status
) values ( 113,
           13,
           63,
           6,
           390.00,
           'DELIVERED' );
insert into orders (
   customer_id,
   shop_id,
   courier_id,
   coupon_id,
   total_price,
   status
) values ( 114,
           14,
           64,
           null,
           500.00,
           'DELIVERED' );
insert into orders (
   customer_id,
   shop_id,
   courier_id,
   coupon_id,
   total_price,
   status
) values ( 115,
           15,
           65,
           null,
           330.00,
           'SHIPPED' );
insert into orders (
   customer_id,
   shop_id,
   courier_id,
   coupon_id,
   total_price,
   status
) values ( 116,
           16,
           66,
           7,
           390.00,
           'DELIVERED' );
insert into orders (
   customer_id,
   shop_id,
   courier_id,
   coupon_id,
   total_price,
   status
) values ( 117,
           17,
           67,
           null,
           280.00,
           'PENDING' );
insert into orders (
   customer_id,
   shop_id,
   courier_id,
   coupon_id,
   total_price,
   status
) values ( 118,
           18,
           68,
           null,
           250.00,
           'DELIVERED' );
insert into orders (
   customer_id,
   shop_id,
   courier_id,
   coupon_id,
   total_price,
   status
) values ( 119,
           19,
           69,
           8,
           350.00,
           'SHIPPED' );
insert into orders (
   customer_id,
   shop_id,
   courier_id,
   coupon_id,
   total_price,
   status
) values ( 120,
           20,
           70,
           null,
           185.00,
           'DELIVERED' );
insert into orders (
   customer_id,
   shop_id,
   courier_id,
   coupon_id,
   total_price,
   status
) values ( 121,
           21,
           71,
           null,
           520.00,
           'DELIVERED' );
insert into orders (
   customer_id,
   shop_id,
   courier_id,
   coupon_id,
   total_price,
   status
) values ( 122,
           22,
           72,
           null,
           540.00,
           'PENDING' );
insert into orders (
   customer_id,
   shop_id,
   courier_id,
   coupon_id,
   total_price,
   status
) values ( 123,
           23,
           73,
           null,
           220.00,
           'DELIVERED' );
insert into orders (
   customer_id,
   shop_id,
   courier_id,
   coupon_id,
   total_price,
   status
) values ( 124,
           24,
           74,
           null,
           480.00,
           'SHIPPED' );
insert into orders (
   customer_id,
   shop_id,
   courier_id,
   coupon_id,
   total_price,
   status
) values ( 125,
           25,
           75,
           null,
           199.00,
           'DELIVERED' );

-- 3. ORDER DETAILS TABLOSU İÇİN 25 ÖRNEK VERİ
insert into orderdetails (
   order_id,
   product_id,
   quantity,
   unit_price
) values ( 1,
           1,
           2,
           250.00 );
insert into orderdetails (
   order_id,
   product_id,
   quantity,
   unit_price
) values ( 2,
           2,
           1,
           320.00 );
insert into orderdetails (
   order_id,
   product_id,
   quantity,
   unit_price
) values ( 3,
           3,
           1,
           180.00 );
insert into orderdetails (
   order_id,
   product_id,
   quantity,
   unit_price
) values ( 4,
           4,
           1,
           150.00 );
insert into orderdetails (
   order_id,
   product_id,
   quantity,
   unit_price
) values ( 5,
           5,
           2,
           120.00 );
insert into orderdetails (
   order_id,
   product_id,
   quantity,
   unit_price
) values ( 6,
           6,
           1,
           290.00 );
insert into orderdetails (
   order_id,
   product_id,
   quantity,
   unit_price
) values ( 7,
           7,
           4,
           210.00 );
insert into orderdetails (
   order_id,
   product_id,
   quantity,
   unit_price
) values ( 8,
           8,
           1,
           350.00 );
insert into orderdetails (
   order_id,
   product_id,
   quantity,
   unit_price
) values ( 9,
           9,
           5,
           95.00 );
insert into orderdetails (
   order_id,
   product_id,
   quantity,
   unit_price
) values ( 10,
           10,
           1,
           450.00 );
insert into orderdetails (
   order_id,
   product_id,
   quantity,
   unit_price
) values ( 11,
           11,
           2,
           165.00 );
insert into orderdetails (
   order_id,
   product_id,
   quantity,
   unit_price
) values ( 12,
           12,
           3,
           140.00 );
insert into orderdetails (
   order_id,
   product_id,
   quantity,
   unit_price
) values ( 13,
           13,
           1,
           390.00 );
insert into orderdetails (
   order_id,
   product_id,
   quantity,
   unit_price
) values ( 14,
           14,
           1,
           500.00 );
insert into orderdetails (
   order_id,
   product_id,
   quantity,
   unit_price
) values ( 15,
           15,
           3,
           110.00 );
insert into orderdetails (
   order_id,
   product_id,
   quantity,
   unit_price
) values ( 16,
           16,
           2,
           195.00 );
insert into orderdetails (
   order_id,
   product_id,
   quantity,
   unit_price
) values ( 17,
           17,
           1,
           280.00 );
insert into orderdetails (
   order_id,
   product_id,
   quantity,
   unit_price
) values ( 18,
           18,
           10,
           25.00 );
insert into orderdetails (
   order_id,
   product_id,
   quantity,
   unit_price
) values ( 19,
           19,
           2,
           175.00 );
insert into orderdetails (
   order_id,
   product_id,
   quantity,
   unit_price
) values ( 20,
           20,
           1,
           185.00 );
insert into orderdetails (
   order_id,
   product_id,
   quantity,
   unit_price
) values ( 21,
           21,
           2,
           260.00 );
insert into orderdetails (
   order_id,
   product_id,
   quantity,
   unit_price
) values ( 22,
           22,
           4,
           135.00 );
insert into orderdetails (
   order_id,
   product_id,
   quantity,
   unit_price
) values ( 23,
           23,
           1,
           220.00 );
insert into orderdetails (
   order_id,
   product_id,
   quantity,
   unit_price
) values ( 24,
           24,
           2,
           240.00 );
insert into orderdetails (
   order_id,
   product_id,
   quantity,
   unit_price
) values ( 25,
           25,
           1,
           199.00 );

commit;

-- 4. KARIŞIK İŞLEMLER İÇİN PL/SQL SİPARİŞ PROSEDÜRÜ
create or replace procedure processcheckout (
   p_customer_id in number,
   p_shop_id     in number,
   p_product_id  in number,
   p_quantity    in number,
   p_unit_price  in number
) as
   v_new_order_id number;
   v_total_price  number;
begin
   v_total_price := p_quantity * p_unit_price;
   insert into orders (
      customer_id,
      shop_id,
      total_price,
      status
   ) values ( p_customer_id,
              p_shop_id,
              v_total_price,
              'PREPARING' ) returning order_id into v_new_order_id;

   insert into orderdetails (
      order_id,
      product_id,
      quantity,
      unit_price
   ) values ( v_new_order_id,
              p_product_id,
              p_quantity,
              p_unit_price );

   commit;
   dbms_output.put_line('Sipariş Onaylandı! ID: ' || v_new_order_id);
exception
   when others then
      rollback;
      dbms_output.put_line('Hata oluştu, işlem geri alındı: ' || sqlerrm);
end processcheckout;
/

-- 5. HOCAYA GÖSTERİLECEK ÖRNEK SORGULAMA (ŞOV KISMI)
-- En çok sipariş alan ve 500 TL üzeri ciro yapan mağazalar:
select s.name as magaza_adi,
       count(distinct o.order_id) as toplam_siparis,
       sum(od.quantity * od.unit_price) as toplam_ciro
  from shop s
  join orders o
on s.shop_id = o.shop_id
  join orderdetails od
on o.order_id = od.order_id
 group by s.name
having sum(od.quantity * od.unit_price) > 500
 order by toplam_ciro desc;